#!/usr/bin/env python3
"""
AUTO-GENERATED dirty prototype test MCP server.
Source: query catalog workbook. Regenerate with build_prototype_server.py
rather than hand-editing tool definitions -- hand-edit the MOCK RESPONSE
bodies in MOCKS (or replace _run_mock's body with a real query call)
instead.

Run:
    python3 catalog_prototype_server.py

Then point Claude Desktop's MCP config at this file (see SETUP.md).
"""
import json
import logging
from mcp.server.mcpserver import MCPServer

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("catalog-prototype")

server = MCPServer("loyalty-query-catalog-prototype")

MOCKS = {}
ENTRY_META = {}


def _run_mock(slug: str, arguments: dict) -> str:
    """Shared body for every generated tool function below.

    LOGGING: this line is your selection log. Every call here is one
    row for the Misselection Log tab -- (entry picked, arguments the
    model extracted). Pipe stdout/stderr to a file during testing and
    review weekly, per Phase 7 of the query catalog.
    """
    meta = ENTRY_META.get(slug, {})
    mock = MOCKS.get(slug)
    if mock is None:
        return json.dumps({"error": f"Unknown tool {slug}"})

    arguments = {k: v for k, v in arguments.items() if v is not None}
    logger.info(json.dumps({
        "event": "tool_selected",
        "entry_id": meta.get("id"),
        "entry_name": meta.get("name"),
        "entry_class": meta.get("class"),
        "arguments": arguments,
    }))

    payload = dict(mock)
    payload["_prototype_note"] = (
        "This is MOCKED data for catalog-selection testing. Replace "
        "the matching entry in MOCKS (or this function's caller) "
        "with a real query once selection tests clean for this entry."
    )
    payload["_arguments_received"] = arguments
    return json.dumps(payload, indent=2)


# --- Entry 1: Customer Points Balance Lookup (Exact or refuse) ---
MOCKS['customer_points_balance_lookup'] = {"type": "mock_result", "entry_id": 1, "entry_name": "Customer Points Balance Lookup", "exact_current_points_balance_for_the_ide": 10476, "points_pending_if_applicable_and_tracked": 0, "points_expiring_soon_if_applicable_with_": "429 pts expiring 2026-07-13", "last_points_activity_date": "2026-03-27"}
ENTRY_META['customer_points_balance_lookup'] = {'id': 1, 'name': 'Customer Points Balance Lookup', 'class': 'Exact or refuse'}
def tool_customer_points_balance_lookup(customer_identifier: str, include_pending: str | None = None, include_expiring: str | None = None) -> str:
    return _run_mock('customer_points_balance_lookup', {'customer_identifier': customer_identifier, 'include_pending': include_pending, 'include_expiring': include_expiring})
server.add_tool(tool_customer_points_balance_lookup, name='customer_points_balance_lookup', description="Returns the exact current points balance for a single identified customer. Must match customer by email address or customer ID. Used by CSMs and merchants when helping an individual shopper resolve a points question or issue. This is exact or refuse\u2014no approximation.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Approximate or estimated balances** \u2192 This is exact or refuse. If customer not found, you get explicit refusal, never an estimate.\n- **Points balances for multiple customers at once** \u2192 Use \"Customer list export with filters\" instead (Entry #6). This is for one customer only.\n- **Historical balances for past dates** \u2192 Use \"Customer points history\" (Entry #3) to see balance at past dates. This shows current balance only.\n- **Points broken down by earning source** (purchase vs. referral vs. sign-up) \u2192 Use \"Points origin breakdown\" for aggregate analysis. For one customer's breakdown, use \"Customer points history\" (Entry #3) which shows each transaction's source.\n- **Custom points report by date ranges** \u2192 Use \"Customer points history\" (Entry #3) if you need \"points earned before X date, current balance, redeemed after Y date\". Evidence: Melinda Maria Designs - \"Need custom breakdown for expiration management.\"\n- **Why points haven't posted yet** \u2192 Use \"Transaction points details\" (Entry #5) instead. This shows current posted balance, not pending or problematic transactions.\n- **Points balance in dollars** \u2192 This returns points count. For dollar value, see redemption value in your program settings. For aggregate dollar liability, use \"Points activity and outstanding balance\" (Entry #14).\n- **Whether customer is \"close to\" redeeming** \u2192 Subjective interpretation. This gives exact balance; you decide what \"close to\" means for your reward thresholds.\n\nPARAMETERS:\n- customer_identifier (required): email address OR customer ID\n- include_pending (optional): whether to show pending points\n- include_expiring (optional): whether to show points expiring soon with dates")

# --- Entry 2: Customer Tier Status Lookup (Exact or refuse) ---
MOCKS['customer_tier_status_lookup'] = {"type": "mock_result", "entry_id": 2, "entry_name": "Customer Tier Status Lookup", "current_tier_name_for_the_identified_cus": "Silver", "date_they_entered_current_tier": "2026-05-20", "days_in_current_tier": 109, "tier_expiration_date_if_applicable_if_ti": "2025-08-18", "next_tier_name_and_requirements_if_not_a": "Bronze", "points_to_next_tier_if_progression_param": 9674}
ENTRY_META['customer_tier_status_lookup'] = {'id': 2, 'name': 'Customer Tier Status Lookup', 'class': 'Exact or refuse'}
def tool_customer_tier_status_lookup(customer_identifier: str, include_progression: str | None = None) -> str:
    return _run_mock('customer_tier_status_lookup', {'customer_identifier': customer_identifier, 'include_progression': include_progression})
server.add_tool(tool_customer_tier_status_lookup, name='customer_tier_status_lookup', description="Returns the exact current tier for a single identified customer. Must match customer by email address or customer ID. Used by CSMs and merchants when helping an individual shopper understand their tier benefits or troubleshoot tier-related issues. This is exact or refuse\u2014no approximation.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Tier status for multiple customers at once** \u2192 Use \"Customer list export with filters\" (Entry #6) instead. This is for one customer only.\n- **Predictions about future tier status** \u2192 Use \"At-risk tier customers\" for customers likely to drop tiers. This shows current tier only, not predictions.\n- **Questions about whether customer \"should\" be in a different tier** \u2192 Debugging question\u2014escalate to support. This returns what the system shows, not validation of tier calculation logic.\n- **Tier status as of past dates** \u2192 Use \"Customer points history\" (Entry #3) or \"Historical tier distribution\" to understand tier at past dates. This shows current tier only.\n- **Whether someone is \"close to\" the next tier** \u2192 Use \"Tier progression\" parameter to see exact distance. \"Close\" is subjective\u2014this returns exact points to next tier.\n- **Why customer's tier is different from what they expect** \u2192 Debugging question. This returns current tier; if unexpected, escalate to support for tier calculation validation.\n\nPARAMETERS:\n- customer_identifier (required): email address OR customer ID\n- include_progression (optional): show exact points/spend needed to reach next tier")

# --- Entry 3: Customer Points History (Exact or refuse) ---
MOCKS['customer_points_history'] = {"type": "mock_result", "entry_id": 3, "entry_name": "Customer Points History", "chronological_list_of_all_points_transac": 6912, "each_transaction_includes_date_time_type": "2026-07-14", "running_balance_after_each_transaction_o": 488, "summary_totals_lifetime_earned_lifetime_": 3270, "date_range_covered": "2026-04-10"}
ENTRY_META['customer_points_history'] = {'id': 3, 'name': 'Customer Points History', 'class': 'Exact or refuse'}
def tool_customer_points_history(customer_identifier: str, start_date: str | None = None, end_date: str | None = None, transaction_types: str | None = None, include_running_balance: str | None = None) -> str:
    return _run_mock('customer_points_history', {'customer_identifier': customer_identifier, 'start_date': start_date, 'end_date': end_date, 'transaction_types': transaction_types, 'include_running_balance': include_running_balance})
server.add_tool(tool_customer_points_history, name='customer_points_history', description="Returns the complete points transaction history for a single identified customer. Shows all points earned, redeemed, expired, and adjusted with dates, reasons, and sources. Used by CSMs and merchants when debugging a customer's points concern or verifying transaction history. This is exact or refuse\u2014returns actual transaction log, not summary statistics.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Points history for multiple customers** \u2192 Use \"Customer list export with filters\" (Entry #6) for bulk export. This is for one customer only.\n- **Summary statistics across many customers** \u2192 Use \"Points activity and outstanding balance\" (Entry #14) for aggregate analysis. This is individual customer transaction log.\n- **Predictions about future points activity** \u2192 This is historical transaction log only. Cannot predict future earning/redemption.\n- **Analysis of \"typical\" customer point patterns** \u2192 Use analytical entries for patterns. This is one customer's actual transactions.\n- **Aggregate activity by time period for all customers** \u2192 Use \"Points activity and outstanding balance\" (Entry #14). This is for one customer.\n- **Why a specific transaction didn't earn expected points** \u2192 Use \"Transaction points details\" (Entry #5) for debugging one specific transaction. This shows all transactions chronologically.\n- **Custom date range math** (e.g., \"points earned before June 1, redeemed after July 1\") \u2192 Evidence: Melinda Maria Designs request. This returns all transactions with dates; you can filter the result by date ranges for your analysis.\n\nPARAMETERS:\n- customer_identifier (required): email address OR customer ID\n- start_date (optional): beginning of history window (defaults to customer join date)\n- end_date (optional): end of history window (defaults to today)\n- transaction_types (optional): filter to specific types (earned, redeemed, expired, adjusted)\n- include_running_balance (optional): show balance after each transaction")

# --- Entry 4: Customer Loyalty Profile Summary (Exact or refuse) ---
MOCKS['customer_loyalty_profile_summary'] = {"type": "mock_result", "entry_id": 4, "entry_name": "Customer Loyalty Profile Summary", "customer_identifying_info_name_email_cus": "Diego Doe (marcus@example.com, cust_95181)", "current_points_balance_exact_and_tier_st": 11490, "loyalty_join_date_and_days_since_join": "2025-10-24", "last_points_activity_date_and_type_earne": "2025-12-28", "lifetime_stats_as_loyalty_member": 7423, "points_earned_lifetime_total": 7359}
ENTRY_META['customer_loyalty_profile_summary'] = {'id': 4, 'name': 'Customer Loyalty Profile Summary', 'class': 'Exact or refuse'}
def tool_customer_loyalty_profile_summary(customer_identifier: str, include_recent_activity: str | None = None, include_tier_progression: str | None = None) -> str:
    return _run_mock('customer_loyalty_profile_summary', {'customer_identifier': customer_identifier, 'include_recent_activity': include_recent_activity, 'include_tier_progression': include_tier_progression})
server.add_tool(tool_customer_loyalty_profile_summary, name='customer_loyalty_profile_summary', description="Returns a complete loyalty snapshot for a single identified customer. Combines points balance, tier status, membership date, last activity, and key behavioral stats in one response. Used by CSMs when they need a quick overview before helping a customer, or by merchants reviewing a VIP customer profile. This is exact or refuse\u2014returns actual data for one customer, not averages or estimates.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Profiles for multiple customers** \u2192 Use \"Customer list export with filters\" (Entry #6) instead. This is one customer summary.\n- **Comparative analysis across customers** \u2192 Use analytical entries like \"Customer count by segment\" or \"Revenue by segment\". This is one customer only.\n- **Predictions about customer future behavior** \u2192 This is historical behavioral data. Cannot predict future actions.\n- **Recommendations about what to offer the customer** \u2192 Prescriptive advice, out of scope. This gives you data; you decide the offer strategy.\n- **Customer PII beyond loyalty data** \u2192 Email and name are fine (necessary for identification). Phone numbers, shipping addresses, payment details are out of scope (Shopify domain, privacy boundary).\n- **Why customer's behavior changed** \u2192 This shows the data (orders, spend, activity), not causal analysis.\n- **Customer sentiment or satisfaction** \u2192 Not tracked in loyalty data. Use customer feedback/NPS tools.\n\nPARAMETERS:\n- customer_identifier (required): email address OR customer ID\n- include_recent_activity (optional): show last N transactions (default 5)\n- include_tier_progression (optional): show points/spend to next tier")

# --- Entry 5: Transaction Points Details (Exact or refuse) ---
MOCKS['transaction_points_details'] = {"type": "mock_result", "entry_id": 5, "entry_name": "Transaction Points Details", "order_number_and_date": "2025-10-02", "customer_identifier_name_email_id": "Aisha Doe (marcus@example.com, cust_65392)", "points_earned_on_this_transaction_if_any": 5574, "base_points_amount": 4552, "earning_reason_rule_e_g_1_1_point_on_pur": "Sample Transaction Points Details value", "tier_multiplier_applied_if_any_with_calc": "Silver"}
ENTRY_META['transaction_points_details'] = {'id': 5, 'name': 'Transaction Points Details', 'class': 'Exact or refuse'}
def tool_transaction_points_details(order_identifier: str, include_excluded_products: str | None = None, include_tier_context: str | None = None) -> str:
    return _run_mock('transaction_points_details', {'order_identifier': order_identifier, 'include_excluded_products': include_excluded_products, 'include_tier_context': include_tier_context})
server.add_tool(tool_transaction_points_details, name='transaction_points_details', description="Returns exact points activity for a single specific order or transaction. Shows whether points were earned or redeemed on that order, amount, reason, and any modifiers applied (tier multipliers, excluded products, promotion bonuses, etc.). Used by CSMs and merchants when debugging \"why didn't this order earn points?\" or verifying points posted correctly. This is exact or refuse\u2014returns actual transaction data or explicit refusal if not found.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Bulk transaction analysis across many orders** \u2192 Use \"Points activity and outstanding balance\" (Entry #14) or analytical entries for aggregate analysis. This is for one specific transaction.\n- **Why points SHOULD have posted differently** \u2192 That's tier calculation logic debugging (policy question). This returns what DID happen\u2014if unexpected, escalate to support.\n- **Order fulfillment or payment details** \u2192 Shopify's domain. This returns loyalty points activity only (earned/redeemed).\n- **Product catalog or pricing information** \u2192 Shopify's domain. This shows which products were excluded from points, but not product details.\n- **Predictions about future transactions** \u2192 This is historical transaction data only.\n- **Customer's full points history** \u2192 Use \"Customer points history\" (Entry #3) for all transactions. This is one specific transaction.\n- **Transaction data with tier information at time of purchase** \u2192 Evidence: Fenwick Limited request. This is possible if we track tier at transaction time. Returns customer's tier at time of this transaction if available.\n\nPARAMETERS:\n- order_identifier (required): order number OR transaction ID\n- include_excluded_products (optional): show which SKUs didn't earn points and why\n- include_tier_context (optional): show customer's tier at time of transaction")

# --- Entry 6: Customer List Export (Exact or refuse) ---
MOCKS['customer_list_export'] = {"type": "mock_result", "entry_id": 6, "entry_name": "Customer List Export", "downloadable_csv_file_containing_specifi": "https://example-exports.onrender.com/exports/mock_export_4527.csv", "preview_count_before_generation_verified": 2762, "fields_available_for_export": ["customer_id", "email", "points_balance", "tier", "join_date", "last_activity"], "customer_id_name_email": "Marcus Chen (diego@example.com, cust_22676)", "current_points_balance_exact": 5881, "tier_status_current": "Gold"}
ENTRY_META['customer_list_export'] = {'id': 6, 'name': 'Customer List Export', 'class': 'Exact or refuse'}
def tool_customer_list_export(filter_criteria: str, fields: str | None = None, format: str | None = None, sort_by: str | None = None) -> str:
    return _run_mock('customer_list_export', {'filter_criteria': filter_criteria, 'fields': fields, 'format': format, 'sort_by': sort_by})
server.add_tool(tool_customer_list_export, name='customer_list_export', description="Generates a downloadable file (CSV) containing exact customer loyalty data matching specified filters. Returns exact data for all customers who meet the criteria at time of export. Used by merchants for email campaigns, financial reporting, CRM syncs, and bulk analysis. This is bulk exact-data operation\u2014returns actual customer records, not analytics or estimates.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Exports without any criteria** \u2192 Must specify at least time range OR segment OR tier. Prevents accidental \"export everyone\" which may be too large.\n- **Customer data outside loyalty domain** \u2192 Payment info (Shopify), shipping addresses (PII beyond loyalty), order details beyond points activity (Shopify). This exports loyalty data only: points, tiers, membership info.\n- **Real-time/live data feeds** \u2192 This is a point-in-time snapshot at time of export generation. For live sync, use ESP integration settings.\n- **Exports exceeding 50,000 customers** \u2192 Requires support for large exports (file size, processing time). This is self-serve up to 50K rows.\n- **Scheduled or recurring exports** \u2192 Product feature, not a query. Use export scheduler in dashboard if available.\n- **Exports where count matches dashboard UI display** \u2192 Evidence: Scamp and Dude - \"95k in file vs. 139k shown in UI.\" **This export count is accurate** (verified source data). If it differs from UI, the export is correct\u2014UI may show cached/stale count. Preview step shows verified count before generation.\n- **Klaviyo sync validation** (who was synced when) \u2192 Evidence: Earth Therapeutics - \"Need to know which customers were synced for reconciliation.\" That's integration sync logging, not export. Use ESP integration health report if available.\n\nPARAMETERS:\n- filter_criteria (required): at minimum, specify time range OR segment OR tier OR points range\n  - tier: filter by tier name(s)\n  - points_min / points_max: points balance range\n  - join_date_start / join_date_end: when they joined loyalty\n  - last_activity_start / last_activity_end: when they last earned/redeemed\n  - segment: predefined segment name\n  - days_inactive: customers with no activity for X+ days\n- fields (optional): which columns to include (defaults to standard set: ID, email, points, tier, join date, last activity)\n- format (optional): CSV (default) or JSON\n- sort_by (optional): how to sort rows (points desc, join_date asc, etc.)")

# --- Entry 10: Average Order Value by Segment (Analytical) ---
MOCKS['average_order_value_by_segment'] = {"type": "mock_result", "entry_id": 10, "entry_name": "Average Order Value by Segment", "average_order_value_for_specified_segmen": 146.69, "comparison_aov_for_reference_segment_e_g": 184.32, "percentage_lift_difference_between_segme": 33.4, "growth_rate_vs_comparison_period": 25.1, "trend_over_time_if_time_series_requested": "Sample Average Order Value by Segment value", "distribution_or_breakdown_by_sub_segment": "High Spenders"}
ENTRY_META['average_order_value_by_segment'] = {'id': 10, 'name': 'Average Order Value by Segment', 'class': 'Analytical'}
def tool_average_order_value_by_segment(segment: str, time_range: str, comparison_segment: str | None = None, comparison_period: str | None = None, include_trend: str | None = None) -> str:
    return _run_mock('average_order_value_by_segment', {'segment': segment, 'time_range': time_range, 'comparison_segment': comparison_segment, 'comparison_period': comparison_period, 'include_trend': include_trend})
server.add_tool(tool_average_order_value_by_segment, name='average_order_value_by_segment', description="Returns the average order value (AOV) for customers in a specified segment **for a time period** (week, month, quarter, year, custom range). Handles comparisons across segments (e.g., \"ALM vs non-ALM AOV in Q2\") and across time periods. Used by merchants to understand spending behavior and measure loyalty program lift. This is aggregate analytical data\u2014slight variations acceptable.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **AOV for individual customers** \u2192 Use \"Customer loyalty profile\" (Entry #4) for one customer's purchase data. This is segment-level aggregate.\n- **AOV for specific products or categories** \u2192 Product analytics, not loyalty analytics. This is AOV by customer segment, not by product.\n- **AOV for specific campaigns** \u2192 Use campaign performance entry if available. This is segment-level, not campaign-specific.\n- **Predictions about future AOV** \u2192 This is historical/current aggregate. Cannot predict future behavior.\n- **Prescriptive advice about how to increase AOV** \u2192 This gives you the data (which segments spend more). You decide strategy.\n- **Pre-discount AOV for incrementality analysis** \u2192 Evidence: Travis Mathew - \"Need pre-discount AOV to prove incrementality to finance teams.\" This returns post-discount AOV (actual transaction amount). For pre-discount analysis, that's a separate metric (would need new entry).\n- **Why AOV differs between segments** \u2192 This shows the numbers (difference). Causal analysis (why) is prescriptive/analytical beyond data reporting.\n\nPARAMETERS:\n- segment (required): which segment (ALM, non-ALM, tier name, redeemers, non-redeemers)\n- time_range (required): date range for analysis\n- comparison_segment (optional): compare to another segment (e.g., \"vs. non-ALM\")\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- include_trend (optional): show trend over time")

# --- Entry 11: Repeat Purchase Rate by Segment (Analytical) ---
MOCKS['repeat_purchase_rate_by_segment'] = {"type": "mock_result", "entry_id": 11, "entry_name": "Repeat Purchase Rate by Segment", "repeat_purchase_rate_for_specified_segme": 5.4, "comparison_rpr_for_reference_segment_e_g": "At Risk", "percentage_point_difference_between_segm": 37.7, "growth_rate_vs_comparison_period": 28.6, "trend_over_time_if_time_series_requested": "Sample Repeat Purchase Rate by Segment value", "absolute_counts_repeat_customers_one_tim": 2967}
ENTRY_META['repeat_purchase_rate_by_segment'] = {'id': 11, 'name': 'Repeat Purchase Rate by Segment', 'class': 'Analytical'}
def tool_repeat_purchase_rate_by_segment(segment: str, time_range: str, comparison_segment: str | None = None, comparison_period: str | None = None, include_trend: str | None = None, repeat_definition: str | None = None) -> str:
    return _run_mock('repeat_purchase_rate_by_segment', {'segment': segment, 'time_range': time_range, 'comparison_segment': comparison_segment, 'comparison_period': comparison_period, 'include_trend': include_trend, 'repeat_definition': repeat_definition})
server.add_tool(tool_repeat_purchase_rate_by_segment, name='repeat_purchase_rate_by_segment', description="Returns the percentage of customers in a segment who made more than one purchase **during a time period** (week, month, quarter, custom range). Handles comparisons across segments and across time periods. Compares repeat purchase rate (RPR) across segments to show loyalty program impact on retention. Used by merchants and executives to measure customer retention and loyalty engagement. This is aggregate analytical data\u2014slight variations acceptable.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Whether individual customers are repeat customers** \u2192 Use \"Customer loyalty profile\" (Entry #4) for one customer's order count. This is segment-level aggregate.\n- **Purchase frequency** (orders per customer) \u2192 That's a different metric. This is binary (repeat vs. one-time), not average order count. For frequency, use separate entry.\n- **Predictions about future repeat purchases** \u2192 This is historical/current aggregate. Cannot predict future behavior.\n- **Why customers do or don't repeat purchase** \u2192 This shows the rate (data). Causal analysis (why) is prescriptive/analytical beyond data reporting.\n- **Repeat purchase rate for specific products** \u2192 Product analytics. This is rate by customer segment, not by product.\n- **Repeat purchase definition** (2+ orders vs. 3+ orders vs. frequency threshold) \u2192 Default is \"2+ orders in time period.\" If merchant uses different definition, parameter overrides.\n\nPARAMETERS:\n- segment (required): which segment (ALM, non-ALM, tier name, loyalty members)\n- time_range (required): date range for analysis\n- comparison_segment (optional): compare to another segment (e.g., \"vs. non-ALM\")\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- include_trend (optional): show trend over time\n- repeat_definition (optional): minimum orders to count as \"repeat\" (default: 2)")

# --- Entry 12: Participation Rate (Analytical) ---
MOCKS['participation_rate'] = {"type": "mock_result", "entry_id": 12, "entry_name": "Participation Rate", "participation_rate_for_time_period_loyal": 26.8, "absolute_counts_total_active_loyalty_mem": 574, "growth_rate_vs_comparison_period_rate_ch": 4.0, "trend_over_time_if_time_series_requested": "Sample Participation Rate value", "breakdown_by_new_vs_returning_customers_": [{"date": "2026-06-02", "type": "expired", "amount": -337, "reason": "Order purchase"}, {"date": "2026-07-01", "type": "earned", "amount": 278, "reason": "Referral bonus"}], "segment_penetration_optional_participati": "At Risk"}
ENTRY_META['participation_rate'] = {'id': 12, 'name': 'Participation Rate', 'class': 'Analytical'}
def tool_participation_rate(time_range: str, comparison_period: str | None = None, include_trend: str | None = None, calculation_basis: str | None = None) -> str:
    return _run_mock('participation_rate', {'time_range': time_range, 'comparison_period': comparison_period, 'include_trend': include_trend, 'calculation_basis': calculation_basis})
server.add_tool(tool_participation_rate, name='participation_rate', description="Returns the percentage of purchasing customers who are enrolled in the loyalty program **for a time period OR at a point in time** (snapshot). Handles comparisons across time periods to show program growth. This is the primary metric for measuring program adoption and reach. Calculated as (active loyalty members / purchasing customers) \u00d7 100. Used by merchants and executives to understand loyalty penetration and growth. This is aggregate analytical data\u2014slight variations acceptable.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Individual customer participation status** \u2192 Use \"Customer loyalty profile\" (Entry #4) to check if one customer is enrolled. This is aggregate percentage.\n- **Why customers don't join** \u2192 This shows the rate (data). Causal analysis (why) is prescriptive beyond data reporting.\n- **Predictions about future participation** \u2192 This is historical/current aggregate. Cannot predict future enrollment.\n- **Participation in specific campaigns** \u2192 Use campaign performance entry if available. This is overall program participation, not campaign-specific.\n- **Comparison to other merchants or industry benchmarks** \u2192 Multi-tenant isolation. Cannot show other merchants' data. This shows YOUR participation only.\n- **How to increase participation** \u2192 Prescriptive advice, out of scope. This gives you the rate; you decide enrollment strategy.\n\nPARAMETERS:\n- time_range (required): date range for analysis\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- include_trend (optional): show trend over time\n- calculation_basis (optional): \"Active Loyalty Member\" (default, excludes dormant) or \"all enrolled\" (includes dormant)")

# --- Entry 13: Tier Movement Summary (Analytical) ---
MOCKS['tier_movement_summary'] = {"type": "mock_result", "entry_id": 13, "entry_name": "Tier Movement Summary", "tier_upgrades_count_and_of_tier_members_": "Platinum", "tier_downgrades_count_and_of_tier_member": "Gold", "tier_retention_count_and_who_stayed_in_s": "Silver", "net_tier_retention_rate_retained_upgrade": 17.9, "average_time_to_upgrade_days_from_join_o": "Sample Tier Movement Summary value", "breakdown_by_tier_who_upgraded_to_each_t": "Silver"}
ENTRY_META['tier_movement_summary'] = {'id': 13, 'name': 'Tier Movement Summary', 'class': 'Analytical'}
def tool_tier_movement_summary(time_range: str, tier_name: str | None = None, comparison_period: str | None = None, include_trend: str | None = None, include_time_to_upgrade: str | None = None) -> str:
    return _run_mock('tier_movement_summary', {'time_range': time_range, 'tier_name': tier_name, 'comparison_period': comparison_period, 'include_trend': include_trend, 'include_time_to_upgrade': include_time_to_upgrade})
server.add_tool(tool_tier_movement_summary, name='tier_movement_summary', description="Returns the number and percentage of customers who moved between tiers during a **past** time period. Shows upgrades, downgrades, and retention (stayed in same tier). Includes tier progression metrics like time to upgrade and net retention rate. Used by merchants to understand tier dynamics and program health. This is historical data\u2014for future tier risk, use \"At-risk tier customers\" instead. This is aggregate analytical data\u2014slight variations acceptable.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Who will drop a tier in the future** \u2192 Use \"At-risk tier customers\" for customers likely to downgrade. Evidence: Frank & Eileen - \"Need report showing expected tier shifts due to expiring points.\" This entry shows what DID happen, not what WILL happen.\n- **Which specific customers moved tiers** \u2192 Use \"Customer list export\" (Entry #6) filtered by tier change date for customer names/emails. This returns counts only.\n- **Why customers moved tiers** \u2192 This shows counts and rates (data). Reasons are: achieved spending threshold, points expired, anniversary reset, etc. (policy-driven, not data query).\n- **Whether tier thresholds are \"right\"** \u2192 Prescriptive advice about program design, out of scope. This gives you movement data; you decide if thresholds need adjustment.\n- **Individual customer's tier history** \u2192 Use \"Customer loyalty profile\" (Entry #4) or \"Customer points history\" (Entry #3) for one customer's tier over time. This is aggregate movement counts.\n- **Tier distribution at historical date** \u2192 Use \"Historical tier distribution snapshot\" for state (counts at point in time). This shows movement (events: who upgraded/downgraded), not state.\n- **Predictions about future tier movements** \u2192 This is historical data. Cannot predict future upgrades/downgrades.\n\nPARAMETERS:\n- time_range (required): date range for analysis (historical period)\n- tier_name (optional): focus on specific tier (e.g., \"who upgraded to Gold?\")\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- include_trend (optional): show trend over time\n- include_time_to_upgrade (optional): show average days to upgrade")

# --- Entry 14: Points Activity and Outstanding Balance (Analytical) ---
MOCKS['points_activity_and_outstanding_balance'] = {"type": "mock_result", "entry_id": 14, "entry_name": "Points Activity and Outstanding Balance", "total_points_earned_in_time_period_acros": 10980, "total_points_redeemed_in_time_period": 4374, "total_points_expired_in_time_period_if_a": 11498, "total_points_adjusted_manual_adjustments": 11199, "total_outstanding_points_balance_all_cus": 10617, "net_points_issued_earned_redeemed_expire": 1169}
ENTRY_META['points_activity_and_outstanding_balance'] = {'id': 14, 'name': 'Points Activity and Outstanding Balance', 'class': 'Analytical'}
def tool_points_activity_and_outstanding_balance(time_range: str, activity_types: str | None = None, breakdown_by: str | None = None, comparison_period: str | None = None, include_trend: str | None = None) -> str:
    return _run_mock('points_activity_and_outstanding_balance', {'time_range': time_range, 'activity_types': activity_types, 'breakdown_by': breakdown_by, 'comparison_period': comparison_period, 'include_trend': include_trend})
server.add_tool(tool_points_activity_and_outstanding_balance, name='points_activity_and_outstanding_balance', description="Returns aggregate points activity metrics **for a time period** (week, month, quarter, custom range): total points earned, redeemed, expired, and currently outstanding across all customers. Handles comparisons across time periods. This is **data-only reporting about points volume and flow, NOT financial liability valuation**. Used by merchants for operational reporting and understanding program activity levels. This is aggregate analytical data\u2014slight variations acceptable.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Dollar value of points or financial liability calculation** \u2192 Evidence: Multiple merchants need liability for GAAP/IFRS. For dollar value and accounting liability, see \"Points liability financial report\" (separate entry, may be boundary). This returns points counts only, not dollar conversion.\n- **Points balances for individual customers** \u2192 Use \"Customer points balance lookup\" (Entry #1) or \"Customer list export\" (Entry #6) for individual customer balances. This is aggregate across all customers.\n- **Predictions about future points activity or redemption** \u2192 This is historical/current aggregate. Cannot predict future earning/redemption behavior.\n- **Breakage rate financial implications** \u2192 Breakage rate is data (% of points that expire unused). Financial implications (revenue recognition, deferred liability unwinding) are accounting, not data query.\n- **Accounting treatment or GAAP compliance guidance** \u2192 Financial and accounting advice, out of scope. This gives you points data; your finance team/auditor decides accounting treatment.\n- **Points by earning source** (purchase vs. referral vs. sign-up) \u2192 Use \"Points origin breakdown\" for source-level analysis. Evidence: flaneur.eu - \"Need to differentiate source of earned points.\" This is total activity, not by source.\n- **Why points activity changed** \u2192 This shows the numbers (trend). Causal analysis (why) is prescriptive/analytical beyond data reporting.\n\nPARAMETERS:\n- time_range (required): date range for activity analysis\n- activity_types (optional): filter to specific activities (earned, redeemed, expired, adjusted)\n- breakdown_by (optional): by tier, by earning method (purchase/referral/bonus)\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- include_trend (optional): show trend over time")

# --- Entry 15: Popular Rewards Analysis (Analytical) ---
MOCKS['popular_rewards_analysis'] = {"type": "mock_result", "entry_id": 15, "entry_name": "Popular Rewards Analysis", "top_n_rewards_by_redemption_count_how_ma": "$25 store credit", "top_n_rewards_by_total_points_redeemed_v": 10403, "percentage_of_total_redemptions_each_rew": 9.4, "average_points_per_redemption_by_reward_": 11946, "redemption_trend_over_time_for_specific_": "Sample Popular Rewards Analysis value", "comparison_between_time_periods_e_g_rewa": "Sample Popular Rewards Analysis value"}
ENTRY_META['popular_rewards_analysis'] = {'id': 15, 'name': 'Popular Rewards Analysis', 'class': 'Analytical'}
def tool_popular_rewards_analysis(time_range: str, sort_by: str | None = None, limit: str | None = None, reward_type: str | None = None, comparison_period: str | None = None, include_trend: str | None = None) -> str:
    return _run_mock('popular_rewards_analysis', {'time_range': time_range, 'sort_by': sort_by, 'limit': limit, 'reward_type': reward_type, 'comparison_period': comparison_period, 'include_trend': include_trend})
server.add_tool(tool_popular_rewards_analysis, name='popular_rewards_analysis', description="Returns which rewards are most frequently redeemed **during a time period** (week, month, quarter, custom range) and their redemption volume. Handles comparisons across time periods to show reward popularity trends. Shows reward popularity by count and by points value redeemed. Used by merchants to understand what customers value and optimize reward catalog. This is aggregate analytical data\u2014slight variations acceptable.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Who redeemed specific rewards** \u2192 Use \"Customer list export\" (Entry #6) filtered by redemption activity or \"Customer loyalty profile\" (Entry #4) for one customer's redemptions. This is aggregate popularity counts.\n- **Revenue impact of specific rewards** \u2192 Use \"Revenue by segment\" (Entry #9) comparing redeemers vs. non-redeemers. This shows redemption counts, not revenue analysis.\n- **Predictions about future reward popularity** \u2192 This is historical/current aggregate. Cannot predict future redemption behavior.\n- **Prescriptive advice about which rewards to offer** \u2192 This gives you popularity data; you decide reward strategy based on brand positioning, margins, customer preferences, etc.\n- **Reward cost or margin data** \u2192 Operational/financial data, not loyalty analytics. This shows redemption counts and points spent, not what the rewards cost you.\n- **Why customers prefer certain rewards** \u2192 This shows the popularity (data). Causal analysis (why) requires customer research beyond transaction data.\n- **Reward performance by segment** (which rewards are popular with Gold vs. Silver) \u2192 Separate analysis. This is overall popularity, not segmented.\n\nPARAMETERS:\n- time_range (required): date range for analysis\n- sort_by (optional): \"count\" (default - most frequently redeemed) or \"points_value\" (most points spent)\n- limit (optional): top N rewards to return (default 10)\n- reward_type (optional): filter to specific reward types (discount, free product, free shipping, etc.)\n- comparison_period (optional): compare to previous period\n- include_trend (optional): show trend over time for top rewards")

# --- Entry 16: Purchase Frequency by Segment (Analytical) ---
MOCKS['purchase_frequency_by_segment'] = {"type": "mock_result", "entry_id": 16, "entry_name": "Purchase Frequency by Segment", "average_orders_per_customer_for_specifie": "Sample Purchase Frequency by Segment value", "comparison_frequency_for_reference_segme": "Sample Purchase Frequency by Segment value", "percentage_lift_difference_between_segme": 12.5, "growth_rate_vs_comparison_period": 21.9, "trend_over_time_if_time_series_requested": "Sample Purchase Frequency by Segment value", "absolute_counts_total_orders_total_custo": 2216}
ENTRY_META['purchase_frequency_by_segment'] = {'id': 16, 'name': 'Purchase Frequency by Segment', 'class': 'Analytical'}
def tool_purchase_frequency_by_segment(segment: str, time_range: str, comparison_segment: str | None = None, comparison_period: str | None = None, include_trend: str | None = None) -> str:
    return _run_mock('purchase_frequency_by_segment', {'segment': segment, 'time_range': time_range, 'comparison_segment': comparison_segment, 'comparison_period': comparison_period, 'include_trend': include_trend})
server.add_tool(tool_purchase_frequency_by_segment, name='purchase_frequency_by_segment', description="Returns the average number of orders per customer for a specified segment **for a time period** (week, month, quarter, year, custom range). Handles comparisons across segments (e.g., \"ALM vs non-ALM in Q4\") and across time periods. Shows how frequently customers purchase, not whether they repeat (that's repeat purchase rate). Used by merchants to understand purchase behavior patterns and measure loyalty program impact on shopping frequency. This is aggregate analytical data\u2014slight variations acceptable.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Repeat purchase rate** (binary: did they buy more than once?) \u2192 Use \"Repeat purchase rate by segment\" (Entry #11). This returns average order count, that returns percentage who repeated.\n- **Individual customer's order count** \u2192 Use \"Customer loyalty profile\" (Entry #4) for one customer's order history. This is segment-level aggregate.\n- **Total orders placed** (volume, not per-customer average) \u2192 This is frequency (orders per customer), not total volume. For volume: order count is in behavioral summaries.\n- **Predictions about future purchase frequency** \u2192 This is historical/current aggregate. Cannot predict future behavior.\n- **Why frequency differs between segments** \u2192 This shows the numbers (difference). Causal analysis (why) is prescriptive beyond data reporting.\n- **Which products customers buy** \u2192 Product analytics. This is purchase frequency (how often), not product mix (what they buy).\n\nPARAMETERS:\n- segment (required): which segment (ALM, non-ALM, tier name, redeemers, non-redeemers)\n- time_range (required): date range for analysis\n- comparison_segment (optional): compare to another segment (e.g., \"vs. non-ALM\")\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- include_trend (optional): show trend over time")

# --- Entry 17: Purchasing Customers by Tier (Analytical) ---
MOCKS['purchasing_customers_by_tier'] = {"type": "mock_result", "entry_id": 17, "entry_name": "Purchasing Customers by Tier", "count_of_purchasing_customers_in_each_ti": 4567, "count_of_total_customers_in_each_tier_re": "Silver", "dormant_count_per_tier_in_tier_but_no_pu": "Gold", "activity_rate_per_tier_of_tier_members_w": 38.2, "comparison_across_tiers_which_tier_has_h": "Bronze", "growth_rate_vs_comparison_period_activit": 11.8}
ENTRY_META['purchasing_customers_by_tier'] = {'id': 17, 'name': 'Purchasing Customers by Tier', 'class': 'Analytical'}
def tool_purchasing_customers_by_tier(time_range: str, tier_name: str | None = None, comparison_period: str | None = None, include_trend: str | None = None, activity_threshold: str | None = None) -> str:
    return _run_mock('purchasing_customers_by_tier', {'time_range': time_range, 'tier_name': tier_name, 'comparison_period': comparison_period, 'include_trend': include_trend, 'activity_threshold': activity_threshold})
server.add_tool(tool_purchasing_customers_by_tier, name='purchasing_customers_by_tier', description="Returns the number of customers in each tier who made at least one purchase **during a time period** (week, month, quarter, custom range), distinguished from total tier membership. Shows \"active purchasers\" vs. \"dormant members\" within each tier. Used by merchants to understand true tier engagement and identify dormant VIPs. Evidence: AMOREPACIFIC - \"Need to differentiate between total members in a tier and those actively making purchases.\" This is aggregate analytical data\u2014slight variations acceptable.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Total tier membership counts** \u2192 Use \"Customer count by segment\" (Entry #8) for total tier counts. This shows active purchasers only, not total membership.\n- **Which specific customers are active/dormant** \u2192 Use \"Customer list export\" (Entry #6) filtered by tier + purchase activity for names/emails. This returns counts only.\n- **Why customers are dormant** \u2192 This shows active vs. dormant split (data). Causal analysis (why they stopped) is prescriptive beyond data reporting.\n- **Predictions about which customers will become dormant** \u2192 This is historical/current state. Cannot predict future dormancy.\n- **What dormant customers should be offered** \u2192 Prescriptive advice about retention strategy, out of scope. This gives you the data (who's dormant); you decide the offer.\n- **Tier movement** (who upgraded/downgraded) \u2192 Use \"Tier movement summary\" (Entry #13). This shows active vs. dormant split, not tier changes.\n\nPARAMETERS:\n- time_range (required): date range for measuring purchase activity\n- tier_name (optional): focus on specific tier, otherwise show all tiers\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- include_trend (optional): show trend over time\n- activity_threshold (optional): minimum purchases to count as \"active\" (default: 1)")

# --- Entry 18: At-Risk Tier Customers (Analytical) ---
MOCKS['at_risk_tier_customers'] = {"type": "mock_result", "entry_id": 18, "entry_name": "At-Risk Tier Customers", "list_of_at_risk_customers_with_name_emai": "Jane Novak", "current_tier": "Platinum", "tier_at_risk_which_tier_they_ll_drop_to": "Gold", "points_expiring_amount_and_date": "2026-06-27", "days_until_downgrade": "Sample At-Risk Tier Customers value", "points_needed_to_maintain_tier": 3456}
ENTRY_META['at_risk_tier_customers'] = {'id': 18, 'name': 'At-Risk Tier Customers', 'class': 'Analytical'}
def tool_at_risk_tier_customers(risk_window_days: str, tier_filter: str | None = None, min_risk_amount: str | None = None, sort_by: str | None = None, include_customer_list: str | None = None) -> str:
    return _run_mock('at_risk_tier_customers', {'risk_window_days': risk_window_days, 'tier_filter': tier_filter, 'min_risk_amount': min_risk_amount, 'sort_by': sort_by, 'include_customer_list': include_customer_list})
server.add_tool(tool_at_risk_tier_customers, name='at_risk_tier_customers', description="Returns list of customers who will drop to a lower tier in the near future **within a specified risk window** (e.g., next 30/60/90 days). **A customer is at risk if:** (1) their points are expiring soon and they'll fall below tier threshold, (2) their tier anniversary period is ending without sufficient qualifying activity, or (3) they have insufficient qualifying spend to maintain tier status. Used for proactive retention campaigns and customer success outreach. Evidence: Frank & Eileen - \"Need report showing expected tier shifts due to expiring points.\" This is predictive\u2014for historical tier changes, use \"Tier movement summary\" instead. This is aggregate analytical data\u2014slight variations acceptable (timing estimates may vary).\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Historical tier downgrades that already happened** \u2192 Use \"Tier movement summary\" (Entry #13) instead. This shows future risk, that shows past events.\n- **Why tier thresholds are set at current levels** \u2192 Policy question, not data query. This shows who's at risk given current thresholds.\n- **Whether to change tier thresholds** \u2192 Prescriptive advice, out of scope. This gives you the data (who's at risk), you decide tier strategy.\n- **Individual customer's full tier history** \u2192 Use \"Customer tier status lookup\" (Entry #2) or \"Customer points history\" (Entry #3) for one customer. This is aggregate risk list.\n- **How to prevent tier drops** \u2192 Prescriptive advice about retention tactics. This gives you the data (who's at risk), you decide the campaign strategy.\n- **Tier retention rate** \u2192 Use \"Tier movement summary\" (Entry #13) for retention metrics. This is about future risk, that's about past retention.\n- **Which customers will upgrade** \u2192 This is downgrade risk only. Upgrade prediction would be separate analysis (customer approaching next tier threshold).\n\nPARAMETERS:\n- risk_window_days (required): how far ahead to look (e.g., 30, 60, 90 days)\n- tier_filter (optional): specific tier to check\n- min_risk_amount (optional): only show if losing X+ points\n- sort_by (optional): days_until_downgrade (default), points_at_risk, tier\n- include_customer_list (optional): return customer names/emails or just count (default: count only for privacy)")

# --- Entry 19: Points Origin Breakdown (Analytical) ---
MOCKS['points_origin_breakdown'] = {"type": "mock_result", "entry_id": 19, "entry_name": "Points Origin Breakdown", "total_points_earned_by_source_in_time_pe": 9292, "purchase_points_from_qualifying_transact": 11762, "referral_points_customer_referred_a_frie": 5155, "sign_up_bonus_new_member_welcome_points": 3483, "birthday_anniversary_bonus": "Sample Points Origin Breakdown value", "campaign_promotion_bonus_limited_time_ea": "Sample Points Origin Breakdown value"}
ENTRY_META['points_origin_breakdown'] = {'id': 19, 'name': 'Points Origin Breakdown', 'class': 'Analytical'}
def tool_points_origin_breakdown(time_range: str, source_filter: str | None = None, comparison_period: str | None = None, include_trend: str | None = None, breakdown_by_segment: str | None = None) -> str:
    return _run_mock('points_origin_breakdown', {'time_range': time_range, 'source_filter': source_filter, 'comparison_period': comparison_period, 'include_trend': include_trend, 'breakdown_by_segment': breakdown_by_segment})
server.add_tool(tool_points_origin_breakdown, name='points_origin_breakdown', description="Returns aggregate points earned **for a time period** (week, month, quarter, custom range) broken down by earning source (purchases, referrals, sign-ups, bonuses, manual adjustments, etc.). Shows which earning activities drive the most points issuance. Used by merchants to understand program mechanics effectiveness and earning pattern health. Evidence: flaneur.eu - \"Cannot differentiate source of earned points.\" This is aggregate analytical data\u2014slight variations acceptable.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Points by source for individual customer** \u2192 Use \"Customer points history\" (Entry #3) which shows each transaction's source. This is aggregate across all customers.\n- **Which earning activities are \"best\"** \u2192 Prescriptive judgment, out of scope. This shows volume by source; you decide which sources to emphasize based on your goals (engagement vs. margin vs. viral growth).\n- **Revenue from customers who earned via each source** \u2192 More complex attribution analysis. This shows points volume by source, not revenue by source.\n- **Predictions about future earning patterns** \u2192 This is historical/current aggregate. Cannot predict future source mix.\n- **Cost per point by source** \u2192 Operational/financial data, not loyalty analytics. This shows points volume, not cost.\n- **Why certain sources drive more points** \u2192 This shows the pattern (data). Causal analysis (why) is prescriptive beyond data reporting.\n\nPARAMETERS:\n- time_range (required): date range for analysis\n- source_filter (optional): focus on specific sources\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- include_trend (optional): show trend over time by source\n- breakdown_by_segment (optional): show source mix by tier or member type")

# --- Entry 20: Customer Lifetime Value (LTV) (Analytical) ---
MOCKS['customer_lifetime_value_ltv'] = {"type": "mock_result", "entry_id": 20, "entry_name": "Customer Lifetime Value (LTV)", "average_lifetime_revenue_per_customer_fo": 2804.53, "comparison_ltv_for_reference_segment_e_g": "High Spenders", "percentage_lift_difference_between_segme": 40.0, "ltv_trend_over_time_if_time_series_reque": "Sample Customer Lifetime Value (LTV) value", "breakdown_by_sub_segment_e_g_ltv_by_tier": "Platinum", "average_tenure_days_since_join_for_conte": 151}
ENTRY_META['customer_lifetime_value_ltv'] = {'id': 20, 'name': 'Customer Lifetime Value (LTV)', 'class': 'Analytical'}
def tool_customer_lifetime_value_ltv(segment: str, calculation_window: str | None = None, comparison_segment: str | None = None, include_tenure: str | None = None, include_trend: str | None = None) -> str:
    return _run_mock('customer_lifetime_value_ltv', {'segment': segment, 'calculation_window': calculation_window, 'comparison_segment': comparison_segment, 'include_tenure': include_tenure, 'include_trend': include_trend})
server.add_tool(tool_customer_lifetime_value_ltv, name='customer_lifetime_value_ltv', description="Returns the average total revenue generated per customer since joining the loyalty program **through a specified end date** (realised LTV to date), segmented by membership type (loyalty vs. non-loyalty, by tier, redeemers vs. non-redeemers). Shows long-term value of loyalty members. Used by executives and finance teams to measure program ROI and justify investment. This is aggregate analytical data\u2014slight variations acceptable, not actuarial/predictive LTV modeling.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Predicted future LTV** (predictive modeling) \u2192 This is historical/realized LTV (what customers have spent so far), not predictive LTV (what they're expected to spend). Predictive LTV requires modeling, churn prediction, cohort assumptions.\n- **Individual customer's LTV** \u2192 Use \"Customer loyalty profile\" (Entry #4) for one customer's total revenue. This is segment-level aggregate.\n- **LTV by cohort** (month/year joined) \u2192 This is overall LTV by segment. Cohort-based LTV analysis would be separate entry (more complex\u2014needs retention curves by cohort).\n- **Margin or profit per customer** \u2192 Revenue only, not costs or profit. Loyalty platform tracks revenue, not full P&L.\n- **Customer acquisition cost (CAC) or CAC:LTV ratio** \u2192 CAC is marketing data, not loyalty data. This shows LTV only.\n- **Churn rate or customer lifetime (tenure)** \u2192 Related metrics but different questions. This shows value (dollars), not retention (time) or churn (loss rate).\n\nPARAMETERS:\n- segment (required): which segment (loyalty members, non-loyalty, tier name, redeemers)\n- calculation_window (optional): limit to customers who joined in specific window (e.g., \"customers who joined in 2024\")\n- comparison_segment (optional): compare to another segment\n- include_tenure (optional): show average days since join (provides LTV time context)\n- include_trend (optional): show LTV trend over time (careful\u2014cohort effects can confuse this)")

# --- Entry 21: Customer Acquisition Rate (Analytical) ---
MOCKS['customer_acquisition_rate'] = {"type": "mock_result", "entry_id": 21, "entry_name": "Customer Acquisition Rate", "number_of_new_loyalty_signups_in_time_pe": 2174, "acquisition_rate_signups_per_day_week_mo": 8.0, "growth_rate_vs_comparison_period_signup_": 34.0, "trend_over_time_if_time_series_requested": "Sample Customer Acquisition Rate value", "breakdown_by_acquisition_source_if_avail": [{"date": "2026-03-15", "type": "expired", "amount": 697, "reason": "Order purchase"}, {"date": "2026-06-06", "type": "adjusted", "amount": 241, "reason": "Referral bonus"}], "percentage_of_purchasing_customers_who_j": 11.4}
ENTRY_META['customer_acquisition_rate'] = {'id': 21, 'name': 'Customer Acquisition Rate', 'class': 'Analytical'}
def tool_customer_acquisition_rate(time_range: str, comparison_period: str | None = None, include_trend: str | None = None, breakdown_by_source: str | None = None, include_conversion_rate: str | None = None) -> str:
    return _run_mock('customer_acquisition_rate', {'time_range': time_range, 'comparison_period': comparison_period, 'include_trend': include_trend, 'breakdown_by_source': breakdown_by_source, 'include_conversion_rate': include_conversion_rate})
server.add_tool(tool_customer_acquisition_rate, name='customer_acquisition_rate', description="Returns the number of new customers who joined the loyalty program **during a time period** (week, month, quarter, year, custom range). Shows acquisition velocity, not total program size. Handles comparisons across time periods to show growth trends and optionally breaks down by acquisition source (referral, organic, campaign). Used by merchants and growth teams to measure program adoption and marketing effectiveness. This is aggregate analytical data\u2014slight variations acceptable.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Total program size or current member count** \u2192 Use \"Customer count by segment\" (Entry #8) for \"How many ALMs do I have?\". This shows NEW joins only, not total membership.\n- **Individual customer join dates** \u2192 Use \"Customer loyalty profile\" (Entry #4) or \"Customer list export\" (Entry #6) for individual customer data. This is aggregate acquisition count.\n- **Why customers joined or didn't join** \u2192 This shows acquisition rate (data). Causal analysis (why) is prescriptive beyond data reporting.\n- **Predictions about future acquisition** \u2192 This is historical/current acquisition. Cannot predict future signups.\n- **Customer acquisition cost (CAC)** \u2192 Marketing spend data, not loyalty data. This shows signups, not cost per signup.\n- **Which customers joined** \u2192 Use \"Customer list export\" (Entry #6) filtered by join date for names/emails. This returns count only.\n- **Retention rate of newly acquired customers** \u2192 Use \"Repeat purchase rate\" (Entry #11) filtered to new cohort. This is acquisition count, not retention.\n\nPARAMETERS:\n- time_range (required): date range for measuring new signups\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- include_trend (optional): show signups over time (time series)\n- breakdown_by_source (optional): show acquisition by source (referral, organic, campaign)\n- include_conversion_rate (optional): show % of purchasing customers who joined")

# --- Entry 22: Average Revenue Per Customer by Segment (Analytical) ---
MOCKS['average_revenue_per_customer_by_segment'] = {"type": "mock_result", "entry_id": 22, "entry_name": "Average Revenue Per Customer by Segment", "average_revenue_per_customer_for_specifi": 4190.03, "comparison_to_other_segments_e_g_loyalty": "Inactive 90+ days", "customer_value_lift_between_segments_dif": "High Spenders", "growth_rate_vs_comparison_period": 5.9, "trend_over_time_if_time_series_requested": "Sample Average Revenue Per Customer by Segment value", "total_customers_and_total_revenue_for_tr": 340.82}
ENTRY_META['average_revenue_per_customer_by_segment'] = {'id': 22, 'name': 'Average Revenue Per Customer by Segment', 'class': 'Analytical'}
def tool_average_revenue_per_customer_by_segment(segment: str, time_range: str, comparison_segment: str | None = None, comparison_period: str | None = None, include_trend: str | None = None) -> str:
    return _run_mock('average_revenue_per_customer_by_segment', {'segment': segment, 'time_range': time_range, 'comparison_segment': comparison_segment, 'comparison_period': comparison_period, 'include_trend': include_trend})
server.add_tool(tool_average_revenue_per_customer_by_segment, name='average_revenue_per_customer_by_segment', description="Returns the average total revenue per customer from a specified segment **for a time period** (week, month, quarter, year, custom range). This is unit economics\u2014\"what's the average customer in this segment worth?\" not \"how much total revenue did the segment generate?\". Handles comparisons across segments (e.g., \"Gold vs Silver customer value\") and across time periods. Used by merchants and executives to understand customer value by segment and prioritize retention/acquisition investments. This is aggregate analytical data\u2014slight variations acceptable.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Total revenue from segment** \u2192 Use \"Revenue by segment\" (Entry #9) for \"How much did Gold tier generate?\". This shows per-customer average, not total dollars.\n- **Revenue from individual customers** \u2192 Use \"Customer loyalty profile\" (Entry #4) for one customer's total revenue. This is segment-level average.\n- **Customer lifetime value (LTV) prediction** \u2192 This is realized revenue to date (historical), not predicted future value (modeling). For realized LTV since joining, use \"Customer lifetime value\" (Entry #20).\n- **Revenue per order (AOV)** \u2192 Use \"Average order value\" (Entry #10). This is total revenue per customer (all orders), not average per single order.\n- **Profit or margin per customer** \u2192 Revenue only, not costs or profit. Loyalty platform tracks revenue, not full P&L.\n- **Why certain segments have higher customer value** \u2192 This shows the numbers (difference). Causal analysis (why) is prescriptive beyond data reporting.\n- **Which customers should be prioritized** \u2192 Prescriptive advice about resource allocation. This gives you customer value data; you decide prioritization based on value, cost to serve, retention risk, etc.\n\nPARAMETERS:\n- segment (required): which segment (ALM, non-ALM, tier name, redeemers, non-redeemers)\n- time_range (required): date range for analysis\n- comparison_segment (optional): compare to another segment\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- include_trend (optional): show revenue per customer over time")

# --- Entry 23: Financial Liability Valuation (Boundary) ---
MOCKS['financial_liability_valuation'] = {"type": "refusal", "message": "**Refusal response:**\n\"Financial liability valuation and accounting treatment require specialized reporting that accounts for regulatory compliance (GAAP/IFRS), breakage assumptions, and auditor requirements. \n\nFor accurate financial liability reporting, please access the **dedicated Liability Reports section** [link if available] or contact your CSM for financial reporting support tailored to your accounting needs.\n\n**I can provide points activity data** if that would be helpful:\n- Outstanding points balance (points count, not dollar value)\n- Points earned, redeemed, expired (points counts)\n- Redemption rate (% of points redeemed)\n- Points activity trends over time\n\nWould any of those help with your analysis?\""}
ENTRY_META['financial_liability_valuation'] = {'id': 23, 'name': 'Financial Liability Valuation', 'class': 'Boundary'}
def tool_financial_liability_valuation() -> str:
    return _run_mock('financial_liability_valuation', {})
server.add_tool(tool_financial_liability_valuation, name='financial_liability_valuation', description="This entry is selected when the question asks for **financial valuation or accounting treatment** of points liability, rather than points activity data. Evidence: Multiple merchants (Travis Mathew, Murad, others from Bagel) need dollar liability values for GAAP/IFRS compliance, balance sheet reporting, and auditor requirements. These questions require specialized financial reporting that accounts for regulatory compliance, breakage assumptions, deferred revenue treatment, and balance sheet accuracy\u2014not yet implemented in self-serve queries.\n\nDOES NOT ANSWER / BOUNDARIES:\n**Triggers:**\n- \"What's my points liability worth in dollars?\"\n- \"What's the balance sheet value of unredeemed points?\"\n- \"How much did we spend on rewards vs. revenue?\"\n- \"What's my points liability for financial statements?\"\n- \"GAAP liability reporting for points\"\n- \"IFRS points liability calculation\"\n- \"Breakage rate financial impact\"\n- \"Points liability for auditors\"\n- \"Deferred revenue from unredeemed points\"\n- \"What's the dollar value of outstanding points?\"")

# --- Entry 24: Payment and Order Fulfillment Data (Boundary) ---
MOCKS['payment_and_order_fulfillment_data'] = {"type": "refusal", "message": "**Refusal response:**\n\"I can only access **loyalty program data** (points, tiers, redemptions, loyalty member behavior). \n\nFor **payment information, order fulfillment, shipping status, and inventory** questions, please check:\n- **Shopify admin** for order details, fulfillment, and inventory\n- **Your payment processor** for payment method details\n- **Shipping carrier** for tracking information\n\n**I can help with loyalty-related questions about this order** if needed:\n- Points earned or redeemed on the order\n- Customer's tier status at time of purchase\n- Why points didn't post (if loyalty-related issue)\n\nWould any of those help?\""}
ENTRY_META['payment_and_order_fulfillment_data'] = {'id': 24, 'name': 'Payment and Order Fulfillment Data', 'class': 'Boundary'}
def tool_payment_and_order_fulfillment_data() -> str:
    return _run_mock('payment_and_order_fulfillment_data', {})
server.add_tool(tool_payment_and_order_fulfillment_data, name='payment_and_order_fulfillment_data', description="This entry is selected when the question asks for payment methods, shipping status, inventory, or other ecommerce data that lives in Shopify's domain, not in the loyalty application. These questions should be directed to Shopify admin or relevant apps. The loyalty platform tracks loyalty program activity (points, tiers, redemptions), not payment/fulfillment operations.\n\nDOES NOT ANSWER / BOUNDARIES:\n**Triggers:**\n- \"What credit card did customer X use?\"\n- \"Is their payment method expired?\"\n- \"Has order #789 shipped?\"\n- \"What's the delivery date for this order?\"\n- \"Do you have this item in stock?\"\n- \"When will size M be available?\"\n- \"What's the tracking number for this order?\"\n- \"Show me abandoned carts\"\n- \"Which payment gateway was used?\"\n- \"Customer's billing address\"\n- \"Shipping address for order #123\"")

# --- Entry 25: Store Policies and Prescriptive Business Advice (Boundary) ---
MOCKS['store_policies_and_prescriptive_business_advice'] = {"type": "refusal", "message": "**Refusal response:**\n**For store policy questions:**\n\"**Store policies** (returns, shipping, hours, locations) are set by you in your Shopify settings and documentation, not in the loyalty program. \n\nI can help with **loyalty program data and analytics** if you have questions about your program performance. Would you like to see metrics like participation rate, tier distribution, or reward popularity?\"\n\n**For prescriptive advice:**\n\"I can provide **data and analytics** about your loyalty program performance, but I can't prescribe specific program changes or configurations yet. \n\nFor **strategic advice** about program optimization, please **contact your CSM** who can:\n- Review your program goals and constraints\n- Analyze your customer base and competitive landscape  \n- Recommend configurations based on similar merchants\n- Help you test and measure program changes\n\n**Data I can show you** that might inform your decisions:\n- Tier performance comparison (revenue, AOV, retention by tier)\n- Reward popularity (which rewards get redeemed most)\n- Participation trends (enrollment and engagement over time)\n- Member behavior patterns (spend, frequency, redemption rates)\n- Program ROI metrics (lift from loyalty vs. non-loyalty)\n\nWould any of those help with your analysis?\""}
ENTRY_META['store_policies_and_prescriptive_business_advice'] = {'id': 25, 'name': 'Store Policies and Prescriptive Business Advice', 'class': 'Boundary'}
def tool_store_policies_and_prescriptive_business_advice() -> str:
    return _run_mock('store_policies_and_prescriptive_business_advice', {})
server.add_tool(tool_store_policies_and_prescriptive_business_advice, name='store_policies_and_prescriptive_business_advice', description="This entry is selected when the question asks for **store policies** (return policy, shipping policy) or **prescriptive advice** about how to configure or optimize the loyalty program. The first belongs in merchant documentation, not loyalty data queries. The second requires strategic consulting context we don't have: merchant goals, constraints, brand positioning, competitive landscape, customer base characteristics, and margin structure.\n\nDOES NOT ANSWER / BOUNDARIES:\n**Triggers:**\n**Store policies:**\n- \"What's your return policy?\"\n- \"What's your shipping policy?\"\n- \"How do I change my store theme?\"\n- \"What are my store hours?\"\n- \"Where is my store located?\"\n\n**Prescriptive advice:**\n- \"Should I set my tier threshold to $500 or $1000?\"\n- \"What's the optimal points-to-dollar ratio?\"\n- \"How do I increase engagement?\"\n- \"What tier structure should I use?\"\n- \"How do I make my program better?\"\n- \"Should I add more rewards?\"\n- \"How do I get more customers to redeem?\"\n- \"What's the best way to structure my tiers?\"\n- \"How many tiers should I have?\"\n- \"Should I offer free shipping or percentage discounts?\"")

# --- Entry 26: Cross-Merchant Comparisons and Benchmarks (Boundary) ---
MOCKS['cross_merchant_comparisons_and_benchmarks'] = {"type": "refusal", "message": "**Refusal response:**\n\"I can only access **your loyalty program data**. For privacy and data security, each merchant's data is completely isolated\u2014I cannot compare your metrics to other merchants or provide industry benchmarks.\n\n**I can help you track your own program's performance over time** and identify trends in your data:\n- **Period-over-period comparisons:** Compare your current metrics to last month, last quarter, or last year\n- **Trend analysis:** See how your participation, revenue, or engagement is changing over time\n- **Segment performance:** Compare different customer segments within YOUR program (tiers, redeemers vs. non-redeemers)\n- **Historical snapshots:** See how your program composition has evolved\n\n**Example questions I can answer:**\n- \\\"How does my current participation rate compare to Q1?\\\"\n- \\\"Is my tier upgrade rate improving or declining?\\\"\n- \\\"Which of MY tiers drives the most revenue?\\\"\n- \\\"How has my redemption rate trended over the past 6 months?\\\"\n\nWould any of those comparisons help you assess your program performance?\""}
ENTRY_META['cross_merchant_comparisons_and_benchmarks'] = {'id': 26, 'name': 'Cross-Merchant Comparisons and Benchmarks', 'class': 'Boundary'}
def tool_cross_merchant_comparisons_and_benchmarks() -> str:
    return _run_mock('cross_merchant_comparisons_and_benchmarks', {})
server.add_tool(tool_cross_merchant_comparisons_and_benchmarks, name='cross_merchant_comparisons_and_benchmarks', description="This entry is selected when the question asks to **compare one merchant's data to other merchants' data** or **industry benchmarks**. Multi-tenant data isolation means each merchant can only access their own data\u2014this is both a security requirement (prevent data leaks) and a privacy commitment (merchants' data is confidential).\n\nDOES NOT ANSWER / BOUNDARIES:\n**Triggers:**\n- \"How does my program compare to other merchants?\"\n- \"What's the industry average participation rate?\"\n- \"Am I doing better or worse than similar stores?\"\n- \"Show me benchmarks for my industry\"\n- \"What are other merchants' tier structures?\"\n- \"How do I rank among your customers?\"\n- \"What's a good participation rate?\"\n- \"Is my redemption rate normal?\"\n- \"Are my metrics above or below average?\"\n- \"What do other apparel brands do for tiers?\"")

# --- Entry 27: Future Predictions and Forecasting (Boundary) ---
MOCKS['future_predictions_and_forecasting'] = {"type": "refusal", "message": "**Refusal response:**\n\"I can show you **historical trends and current metrics**, but I cannot predict future behavior or performance. Forecasting requires statistical models, seasonality adjustments, and assumptions about future conditions that are outside my scope.\n\n**Historical data I can provide to inform your planning:**\n- **Past trends:** How metrics have changed over time (e.g., \"participation rate grew 15% from Q1 to Q2\")\n- **Current state:** Your program's current composition (customers, tiers, revenue, points)\n- **Historical patterns:** Seasonal trends, tier movement rates, redemption cycles from your past data\n- **Segment performance:** Which customer groups have driven growth historically\n\n**Example questions I can answer:**\n- \"How has my customer acquisition rate trended over the past 6 months?\"\n- \"What's my current run rate for tier upgrades?\"\n- \"Show me seasonal patterns in redemption behavior\"\n- \"How did revenue grow from Q1 to Q3?\"\n- \"What percentage of customers typically upgrade within 90 days?\" (historical rate, not prediction)\n\nFor **forecasting and predictions**, you might consider:\n- **Spreadsheet projections:** Export historical data and build your own forecast model\n- **BI tool forecasting:** Tools like Looker, Tableau, or Mode have built-in forecasting features\n- **Your finance team:** They likely have forecasting methodologies that incorporate loyalty data alongside other business drivers\n\nWould historical trend data help with your planning?\""}
ENTRY_META['future_predictions_and_forecasting'] = {'id': 27, 'name': 'Future Predictions and Forecasting', 'class': 'Boundary'}
def tool_future_predictions_and_forecasting() -> str:
    return _run_mock('future_predictions_and_forecasting', {})
server.add_tool(tool_future_predictions_and_forecasting, name='future_predictions_and_forecasting', description="This entry is selected when the question asks for **predictions about future behavior, trends, or metrics**. The loyalty platform tracks historical and current data, but does not generate forecasts, predictions, or \"what if\" scenarios about future performance. Questions like \"How many customers will join next month?\" or \"What will my revenue be in Q4?\" request predictions we cannot make.\n\nDOES NOT ANSWER / BOUNDARIES:\n**Triggers:**\n- \"How many customers will join next month?\"\n- \"What will my revenue be in Q4?\"\n- \"Predict how many people will redeem next week\"\n- \"How many tier upgrades should I expect?\"\n- \"What will my participation rate be next year?\"\n- \"Will this customer churn?\"\n- \"How much will this segment spend next quarter?\"\n- \"When will I hit 10,000 members?\"\n- \"How fast is my program growing?\"\n- \"Project my points liability for next year\"\n- \"What's the expected ROI for the next 6 months?\"\n- \"How many customers will reach Gold tier by year-end?\"")

# --- Entry 7: Loyalty Program ROI Summary (Analytical) ---
MOCKS['loyalty_program_roi_summary'] = {"type": "mock_result", "entry_id": 7, "entry_name": "Loyalty Program ROI Summary", "time_period_for_analysis": "Sample Loyalty Program ROI Summary value", "total_store_revenue_all_customers": 594.08, "revenue_from_loyalty_members_exact": 2691.16, "revenue_from_non_loyalty_members_exact": 3357.92, "loyalty_revenue_share_of_total": 1859.75, "member_count_and_growth_rate_vs_comparis": 4.7}
ENTRY_META['loyalty_program_roi_summary'] = {'id': 7, 'name': 'Loyalty Program ROI Summary', 'class': 'Analytical'}
def tool_loyalty_program_roi_summary(time_range: str, comparison_period: str | None = None, segment: str | None = None, include_incremental_calculation: str | None = None) -> str:
    return _run_mock('loyalty_program_roi_summary', {'time_range': time_range, 'comparison_period': comparison_period, 'segment': segment, 'include_incremental_calculation': include_incremental_calculation})
server.add_tool(tool_loyalty_program_roi_summary, name='loyalty_program_roi_summary', description="Returns overall return on investment metrics for the loyalty program. Shows revenue from loyalty members vs. non-members, member behavior lift (AOV, purchase frequency), and engagement indicators. Used by executives, CFOs, and marketing teams to justify program investment and measure program health. This is aggregate analytical data\u2014slight variations acceptable, not exact customer-level accounting.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Specific customer-level ROI** \u2192 Use \"Customer loyalty profile\" (Entry #4) for one customer's behavior. This is program-level aggregate.\n- **Dollar cost of rewards or point liability valuation** \u2192 Use \"Points activity and outstanding balance\" (Entry #14) for points data. For financial liability (dollar value), use points liability report (separate entry). Evidence: multiple merchants need liability for GAAP/IFRS.\n- **Prescriptive advice about how to improve ROI** \u2192 This gives you the data (current performance). You decide strategy changes. Out of scope: \"should I spend more on loyalty?\"\n- **Comparison to other merchants or industry benchmarks** \u2192 Multi-tenant data isolation. Cannot show other merchants' data. This shows YOUR performance only.\n- **ROI for specific campaigns** \u2192 Use campaign attribution entry if available. This is overall program ROI, not campaign-specific.\n- **Pre-discount AOV** for proving incrementality \u2192 Evidence: Travis Mathew - \"Need pre-discount AOV to prove incrementality to finance teams.\" This returns standard AOV. For pre-discount analysis, that's a separate metric (may need new entry).\n- **Why ROI changed** \u2192 This shows the data (revenue, behavior). Causal analysis (why it changed) is prescriptive/analytical beyond data reporting.\n\nPARAMETERS:\n- time_range (required): date range for analysis\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- segment (optional): narrow to specific tier or member type\n- include_incremental_calculation (optional): show how incremental revenue is calculated")

# --- Entry 8: Customer Count by Segment (Analytical) ---
MOCKS['customer_count_by_segment'] = {"type": "mock_result", "entry_id": 8, "entry_name": "Customer Count by Segment", "segment_name_and_definition": "Yuki Kovacs", "exact_count_of_customers_in_specified_se": 4339, "percentage_of_total_customers_if_applica": 12.8, "growth_rate_vs_comparison_period_count_c": 25.8, "trend_over_time_if_time_series_requested": "Sample Customer Count by Segment value", "breakdown_by_sub_segment_if_requested_e_": "VIP"}
ENTRY_META['customer_count_by_segment'] = {'id': 8, 'name': 'Customer Count by Segment', 'class': 'Analytical'}
def tool_customer_count_by_segment(segment: str, time_range: str, comparison_period: str | None = None, include_trend: str | None = None, breakdown: str | None = None) -> str:
    return _run_mock('customer_count_by_segment', {'segment': segment, 'time_range': time_range, 'comparison_period': comparison_period, 'include_trend': include_trend, 'breakdown': breakdown})
server.add_tool(tool_customer_count_by_segment, name='customer_count_by_segment', description="Returns the number of customers in a specified segment **for a time period** (point-in-time snapshot OR growth over a range). Shows current membership size and distribution, not new signups. Handles comparisons across time periods (e.g., \"How many ALMs in Q1 vs Q4?\"). Segments include: total loyalty members (ALM), tier membership, redeemers, repeat customers, purchasing customers. Used by merchants and CSMs to understand program size, tier distribution, and segment composition. This is analytical counting\u2014minor variations acceptable (e.g., customers who just joined might take minutes to appear).\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Individual customer identities** \u2192 Use \"Customer loyalty profile\" (Entry #4) for one customer. This is aggregate count.\n- **List of customers in segment** \u2192 Use \"Customer list export\" (Entry #6) to get customer names/emails. This returns count only.\n- **How many new customers joined the program** \u2192 Use \"Customer acquisition rate\" (Entry #21) for new signups over time. This shows current membership (stock), that shows new joins (flow).\n- **Predictions about future segment size** \u2192 This is historical/current count. Cannot predict future.\n- **Detailed behavior within segments** \u2192 Use behavioral metric entries (AOV, repeat rate, etc.) for behavior analysis. This is count only.\n- **Cross-merchant comparisons** \u2192 Multi-tenant isolation. Cannot show other merchants' counts.\n- **How many customers in each tier made a purchase** \u2192 Evidence: AMOREPACIFIC - \"Need to differentiate between total members in a tier and those actively making purchases.\" That's \"Purchasing customers by tier\" (Entry #17). This shows total tier membership, not active purchasers.\n- **Why segment size changed** \u2192 This shows the count and trend. Causal analysis (why) is prescriptive/analytical beyond counting.\n\nPARAMETERS:\n- segment (required): which segment to count\n  - Options: ALM (active loyalty members), specific tier name, redeemers, repeat customers, purchasing customers\n- time_range (required): date range for counting\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- include_trend (optional): show count over time (time series)\n- breakdown (optional): for \"tier\", show count for each tier separately")

# --- Entry 9: Revenue by Segment (Analytical) ---
MOCKS['revenue_by_segment'] = {"type": "mock_result", "entry_id": 9, "entry_name": "Revenue by Segment", "segment_name_and_definition": "Marcus Khan", "time_period_for_analysis": "Sample Revenue by Segment value", "total_revenue_from_specified_segment_exa": 3262.82, "revenue_share_of_total_store_revenue": 1527.71, "comparison_to_other_segments_if_requeste": "At Risk", "growth_rate_vs_comparison_period_revenue": 20.7}
ENTRY_META['revenue_by_segment'] = {'id': 9, 'name': 'Revenue by Segment', 'class': 'Analytical'}
def tool_revenue_by_segment(segment: str, time_range: str, comparison_segment: str | None = None, comparison_period: str | None = None, include_trend: str | None = None, revenue_type: str | None = None) -> str:
    return _run_mock('revenue_by_segment', {'segment': segment, 'time_range': time_range, 'comparison_segment': comparison_segment, 'comparison_period': comparison_period, 'include_trend': include_trend, 'revenue_type': revenue_type})
server.add_tool(tool_revenue_by_segment, name='revenue_by_segment', description="Returns total revenue from a specified customer segment **for a time period** (week, month, quarter, year, custom range). Shows aggregate dollars the segment generated, not per-customer averages. Handles comparisons across segments (e.g., \"ALM vs non-ALM in Q1 2025\") and across time periods. Segments include: loyalty members (ALM) vs. non-members, redeemers vs. non-redeemers, by tier, by repeat customer status. Used by merchants and executives to understand which segments drive revenue and measure loyalty program impact. This is aggregate analytical data\u2014slight variations acceptable.\n\nDOES NOT ANSWER / BOUNDARIES:\n- **Revenue from individual customers** \u2192 Use \"Customer loyalty profile\" (Entry #4) or \"Customer list export\" (Entry #6) for individual customer data. This is aggregate by segment.\n- **Average revenue per customer** \u2192 Use \"Average revenue per customer by segment\" (Entry #22) for unit economics (\"What's the average customer worth?\"). This shows total revenue (\"How much did the segment generate?\"), not per-customer averages.\n- **Revenue from specific products or categories** \u2192 Product analytics, not loyalty analytics. This is revenue by customer segment, not by product.\n- **Revenue from specific campaigns** \u2192 Use campaign attribution entry if available. This is segment-level, not campaign-specific.\n- **Prescriptive advice about how to increase revenue** \u2192 This gives you the data (which segments generate revenue). You decide strategy.\n- **Profit or margin data** \u2192 Revenue only, not costs or profit. Loyalty platform tracks revenue, not full P&L.\n- **\"Actual revenue\" vs. \"added revenue\" distinction** \u2192 Evidence: Murad - \"Dashboard doesn't provide actual revenue, only added revenue.\" This entry returns **actual revenue** (what the segment spent). For \"added revenue\" (incremental lift calculation), specify in parameters or use ROI entry.\n- **Pre-discount revenue** \u2192 Evidence: Travis Mathew - \"Need pre-discount AOV to prove incrementality.\" This returns post-discount revenue (actual transaction amount). Pre-discount would need separate entry or parameter.\n\nPARAMETERS:\n- segment (required): which segment (ALM, non-ALM, redeemers, non-redeemers, specific tier name, repeat customers)\n- time_range (required): date range for analysis\n- comparison_segment (optional): compare to another segment (e.g., \"vs. non-ALM\")\n- comparison_period (optional): compare to previous period, YoY, QoQ\n- include_trend (optional): show revenue over time (time series)\n- revenue_type (optional): \"actual\" (default - what they spent) or \"added\" (incremental lift calculation)")


if __name__ == "__main__":
    server.run()
