services:
  - type: web
    name: loyalty-query-catalog-prototype
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 catalog_prototype_server_http.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
